# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title

# Setup
destination: ../_site
title: domusing
tagline: musings in print
description: Thoughts and projects
url: http://www.domusing.com
baseurl: ''
paginate: 5

sass:
  style:  expanded

defaults:
  -
    scope:
      path: ""
    values:
      author: Dom

# Custom vars
version:             1.0.0

# gems
gems: [jekyll-paginate]
